import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainMenu from "../components/MainMenu";
import localFont from "next/font/local";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex" dir="rtl">
        
        <MainMenu />
        <main className='flex-1 p-8 bg-black'>
          {children}
        </main>
      </body>
    </html>
  );
}
